import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useRef } from "react";
import track, { useTracking } from "react-tracking";

import ButtonBlue from "@/components/ButtonBlue";
import ButtonGreen from "@/components/ButtonGreen";
import ButtonYellow from "@/components/ButtonYellow";
import ButtonRed from "@/components/ButtonRed";
import StartButton from "@/components/StartButton";
import ScoreBoard from "@/components/ScoreBoard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Jogo da memória</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        ></link>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>
      <main className={styles.main}>
        <div className={styles.section}>
          <ButtonRed />
          <ButtonBlue />
          <ButtonGreen />
          <ButtonYellow />
        </div>

        <StartButton />
        <ScoreBoard />
      </main>
    </>
  );
}
