import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [color, setColor] = useState("colorGreen");
  const possibleColors = ['colorBlue', 'colorGreen', 'colorRed', 'colorGold'];

  const red = 'colorRed';
  const blue = 'colorBlue';
  const green = 'colorGreen';
  const gold = 'colorGold';

  const randomColorIndex = () => {
    return Math.floor(Math.random() * possibleColors.length);
  }

  const pickColors = () => {
    const array = [];
    for (let i = 0; i < 4; i++) {
      array.push(possibleColors[randomColorIndex()]);
    }
    return array;
  };

  const [pickedColors, setPickedColors] = useState(pickColors());

  useEffect(() => {
    document.getElementById('sequenceButton').onclick = () => {
      setPickedColors(pickColors());
    };
  })

  const clickedColors = [];

  const colorPush = (color) => {
    document.getElementById('square' + color).onclick = () => {
      clickedColors.push('color' + color);
    };
  }

  useEffect(() => {
    colorPush('Blue');
    colorPush('Green');
    colorPush('Red');
    colorPush('Gold');
  })

  const compareArrays = (pickedColors, clickedColors) => {
    if (pickedColors.length !== clickedColors.length)
      return false;
    else {
      // Comparing each element of your array
      for (var i = 0; i < pickedColors.length; i++) {
        if (pickedColors[i] !== clickedColors[i]) {
          return false;
        }
      }
      return true;
    }
  };

  useEffect(() => {
    document.getElementById('verifyResult').onclick = () => {
      if (compareArrays(pickedColors, clickedColors) == true) {
        document.getElementById('textResult').innerHTML = "CORRETO!";
      }
      else {
        document.getElementById('textResult').innerHTML = "ERRADO!";
      }

    };
  })

  const delay = ms => new Promise(
    resolve => setTimeout(resolve, ms)
  );

  const sequencePlay = async event => {

    for (var i = 0; i < pickedColors.length; i++) {
      switch (pickedColors[i]) {
        case 'colorRed':
          document.getElementById('squareRed').classList.add('colorActive');
          await delay(500);
          document.getElementById('squareRed').classList.remove('colorActive');
          await delay(500);
          break;

        case 'colorGreen':
          document.getElementById('squareGreen').classList.add('colorActive');
          await delay(500);
          document.getElementById('squareGreen').classList.remove('colorActive');
          await delay(500);
          break;

        case 'colorBlue':
          document.getElementById('squareBlue').classList.add('colorActive');
          await delay(500);
          document.getElementById('squareBlue').classList.remove('colorActive');
          await delay(500);
          break;

        case 'colorGold':
          document.getElementById('squareGold').classList.add('colorActive');
          await delay(500);
          document.getElementById('squareGold').classList.remove('colorActive');
          await delay(500);
          break;

        default:
          break;
      }
    }
  };

  return (
    <>
      <Head>
        <title>Jogo da memória</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"></link>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      </Head>
      <main className={styles.main}>

        <div className={styles.grid + styles.center}>
          <div className={styles.colorSquare + ' ' + red} id="squareRed" ></div>
        </div>

        <div className={styles.grid + styles.center}>
          <div className={styles.colorSquare + ' ' + blue} id="squareBlue"></div>
        </div>

        <div className={styles.grid + styles.center}>
          <div className={styles.colorSquare + ' ' + green} id="squareGreen"></div>
        </div>

        <div className={styles.grid + styles.center}>
          <div className={styles.colorSquare + ' ' + gold} id="squareGold"></div>
        </div>

        <button className="btn btn-primary" id='sequenceButton' onClick={sequencePlay}>
          Reproduzir sequência
        </button>

        <div id='gameResult'>
          <button id='verifyResult'>
            Verificar
          </button>
          <p id='textResult'>
          </p>
        </div>

      </main>
    </>
  )
}
